<?php
  class CodeRobot_Sniffs_Strings_ProfanityStringSniff implements PHP_CodeSniffer_Sniff {

    /**
     * Returns the token types that this sniff is interested in.
     *
     * @return array(int)
     */
    public function register() {
      return array(
        T_CONSTANT_ENCAPSED_STRING
      );
    }


    /**
     * Processes the tokens that this sniff is interested in.
     *
     * @param PHP_CodeSniffer_File $phpcsFile The file where the token was found.
     * @param int                  $stackPtr  The position in the stack where
     *                                        the token was found.
     *
     * @return void
     */
    public function process(PHP_CodeSniffer_File $phpcsFile, $stackPtr) {
      $tokens = $phpcsFile->getTokens();
      $dirty  = $this->find_dirty($tokens[$stackPtr]['content']);
      if($dirty !== FALSE) {
        $error = 'Profanity found. "' . $dirty . '" is not allowed to be used inside a string.';
        $phpcsFile->addError($error, $stackPtr);
      }
    }


    function find_dirty($text) {
      $bads = array(
        'ass',
        'asses',
        'asshole',
        'assholes',
        'asskisser',
        'asswipe',
        'balls',
        'bastard',
        'beastial',
        'beastiality',
        'beastility',
        'beaver',
        'bestial',
        'bestiality',
        'bitch',
        'bitcher',
        'bitchers',
        'bitches',
        'bitchin',
        'bitching',
        'blow job',
        'blowjob',
        'blowjobs',
        'bonehead',
        'boner',
        'brown eye',
        'browneye',
        'browntown',
        'bullshit',
        'bum',
        'bung hole',
        'butch',
        'butt',
        'buttface',
        'buttfuck',
        'buttfucker',
        'butthead',
        'butthole',
        'buttpicker',
        'chink',
        'christ',
        'circle jerk',
        'clam',
        'clit',
        'cobia',
        'cock',
        'cocks',
        'cocksuck',
        'cocksucked',
        'cocksucker',
        'cocksucking',
        'cocksucks',
        'cooter',
        'crap',
        'cum',
        'cummer',
        'cumming',
        'cums',
        'cumshot',
        'cunilingus',
        'cunillingus',
        'cunnilingus',
        'cunt',
        'cuntlick',
        'cuntlicker',
        'cuntlicking',
        'cunts',
        'cyberfuc',
        'cyberfuck',
        'cyberfucked',
        'cyberfucker',
        'cyberfuckers',
        'cyberfucking',
        'damn',
        'dick',
        'dike',
        'dildo',
        'dildos',
        'dink',
        'dinks',
        'dipshit',
        'dong',
        'douche bag',
        'dumbass',
        'dyke',
        'ejaculate',
        'ejaculated',
        'ejaculates',
        'ejaculating',
        'ejaculatings',
        'ejaculation',
        'fag',
        'fagget',
        'fagging',
        'faggit',
        'faggot',
        'faggs',
        'fagot',
        'fagots',
        'fags',
        'fart',
        'farted',
        'farting',
        'fartings',
        'farts',
        'farty',
        'fatass',
        'fatso',
        'felatio',
        'fellatio',
        'fingerfuck',
        'fingerfucked',
        'fingerfucker',
        'fingerfuckers',
        'fingerfucking',
        'fingerfucks',
        'fistfuck',
        'fistfucked',
        'fistfucker',
        'fistfuckers',
        'fistfucking',
        'fistfuckings',
        'fistfucks',
        'fuck',
        'fucked',
        'fucker',
        'fuckers',
        'fuckin',
        'fucking',
        'fuckings',
        'fuckme',
        'fucks',
        'fuk',
        'fuks',
        'furburger',
        'gangbang',
        'gangbanged',
        'gangbangs',
        'gaysex',
        'gazongers',
        'goddamn',
        'gonads',
        'gook',
        'guinne',
        'hard on',
        'hardcoresex',
        'hell',
        'homo',
        'hooker',
        'horniest',
        'horny',
        'hotsex',
        'hussy',
        'jack off',
        'jackass',
        'jacking off',
        'jackoff',
        'jack-off',
        'jap',
        'jerk',
        'jerk-off',
        'jesus',
        'jew',
        'jism',
        'jiz',
        'jizm',
        'jizz',
        'kike',
        'knob',
        'kock',
        'kondum',
        'kondums',
        'kraut',
        'kum',
        'kummer',
        'kumming',
        'kums',
        'kunilingus',
        'lesbian',
        'lesbo',
        'loser',
        'lust',
        'lusting',
        'merde',
        'mick',
        'mothafuck',
        'mothafucka',
        'mothafuckas',
        'mothafuckaz',
        'mothafucked',
        'mothafucker',
        'mothafuckers',
        'mothafuckin',
        'mothafucking',
        'mothafuckings',
        'mothafucks',
        'motherfuck',
        'motherfucked',
        'motherfucker',
        'motherfuckers',
        'motherfuckin',
        'motherfucking',
        'motherfuckings',
        'motherfucks',
        'mound',
        'muff',
        'nigger',
        'niggers',
        'orgasim',
        'orgasims',
        'orgasm',
        'orgasms',
        'pecker',
        'penis',
        'phonesex',
        'phuk',
        'phuked',
        'phuking',
        'phukked',
        'phukking',
        'phuks',
        'phuq',
        'pimp',
        'piss',
        'pissed',
        'pisser',
        'pissers',
        'pisses',
        'pissin',
        'pissing',
        'pissoff',
        'porn',
        'porno',
        'pornography',
        'pornos',
        'prick',
        'pricks',
        'prostitute',
        'punk',
        'pussies',
        'pussy',
        'pussys',
        'queer',
        'retard',
        'schlong',
        'screw',
        'sheister',
        'shit',
        'shited',
        'shitfull',
        'shiting',
        'shitings',
        'shits',
        'shitted',
        'shitter',
        'shitters',
        'shitting',
        'shittings',
        'shitty',
        'slag',
        'sleaze',
        'slut',
        'sluts',
        'smut',
        'snatch',
        'spunk',
        'twat',
        'wetback',
        'whore',
        'wop'
      );


      for($i = 0; $i < sizeof($bads); $i++) {
        if(preg_match('/\b' . $bads[$i] . '\b/six', $text)) {
          return $bads[$i];
        }
      }
      return FALSE;

    }



  }
